### PR TITLE
Added some math functions

### PR DESCRIPTION
**Pull request by felinis**

### CODE REVIEW

**Comment by TheOnlyZac** [comment]
Thank you for the PR. Does this compile on your machine? Looks like there were some build errors on AppVeyor.

**Comment by felinis** [comment]
You're right, I will fix the code. Some type definitions are missing.

**Comment by TheOnlyZac** [comment]
Thanks, if you can take care of those errors I will handle any potential merge conflicts.

**Comment by felinis** [comment]
Commit [2c5b411](https://github.com/TheOnlyZac/sly1/pull/44/commits/2c5b411f0294e18d9d7843ad0c6e711cf876c908) builds successfully on Linux using GCC 13, but AppVeyor's VS2019 compiler does not. I wanted to test the commit [bfa373d](https://github.com/TheOnlyZac/sly1/pull/44/commits/bfa373ddcca52a5faa823316e72b8f857175cb38) but for some reason AppVeyor does not want to build it.

**Comment by TheOnlyZac** [comment]
Appveyor can’t build it because there are merge conflicts, I’ll take care of it, thank you!

**Comment by felinis** [comment]
You're welcome!

**Review by TheOnlyZac — APPROVED** [review]

**Pull request merged**
